# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
  packages: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - name: Print Maven localRepository
        run: |
          MAVEN_LOCAL=$(mvn -B -q help:evaluate -Dexpression=settings.localRepository -DforceStdout)
          echo "LOCAL_REPO=$MAVEN_LOCAL" | tee -a $GITHUB_ENV
          echo "Maven localRepository = $MAVEN_LOCAL"
      - name: Clear negative Maven cache (if present)
        run: |
          REPO="$HOME/.m2/repository"
          if [ -d "$REPO" ]; then
            rm -rf "$REPO/org/seamless"
            find "$REPO" -name "*.lastUpdated" -delete
          fi
          ls -a $HOME/.m2/
                
      - name: Configure Maven (mirror -> GH Packages + Central) with auth
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <servers>
              <!-- Must match the id used below (gh-mirror) -->
              <server>
                <id>gh-mirror</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
      
            <!-- Redirect any external repo (e.g., 4thline) to GH Packages; keep Central direct -->
            <mirrors>
              <mirror>
                <id>gh-mirror</id>
                <name>Mirror external repos to GH Packages</name>
                <url>https://maven.pkg.github.com/jolson20/cling</url>
                <mirrorOf>external:*,!central</mirrorOf>
              </mirror>
            </mirrors>
      
            <profiles>
              <profile>
                <id>repos</id>
                <repositories>
                  <repository>
                    <id>gh-mirror</id>
                    <url>https://maven.pkg.github.com/jolson20/cling</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                  <repository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
      
            <activeProfiles>
              <activeProfile>repos</activeProfile>
            </activeProfiles>
          </settings>
          XML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
      - name: Build project
        run: mvn -B -U -DskipTests clean package
