name: Build Cling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Checkout your repository
      - uses: actions/checkout@v4

      # 2️⃣  Set up Java 8 (correct toolchain for legacy Maven builds)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      # 3️⃣  Build and install Seamless dependencies locally (~/.m2/repository/org/seamless)
      - name: Build Seamless dependency
        run: |
          git clone https://github.com/4thline/seamless.git
          cd seamless
          mvn clean install -DskipTests

      # 4️⃣  Build Cling core & support (skip Android demo modules + Javadocs)
      - name: Build Cling
        run: |
          mvn -B -U clean package \
              -DskipTests \
              -Dmaven.javadoc.skip=true \
              -pl '!cling-demo-android,!cling-demo-android-browser,!cling-demo-android-light'

      # 5️⃣  Save artifacts (optional)
      - name: Upload Cling JARs
        uses: actions/upload-artifact@v4
        with:
          name: cling-artifacts
          path: |
            core/target/*.jar
            support/target/*.jar
