# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      # Prefetch Seamless deps with retries (only needed first time)
      - name: Prefetch Seamless artifacts
        run: |
          set -e
          for A in org.seamless:seamless-util:1.1.2 \
                   org.seamless:seamless-http:1.1.2 \
                   org.seamless:seamless-xml:1.1.2
          do
            n=0
            until [ $n -ge 6 ]
            do
              mvn -B -U dependency:get \
                -Dartifact="$A" \
                -DrepoUrl=https://4thline.org/m2 \
                -Dmaven.wagon.http.retryHandler.count=5 && break
              n=$((n+1))
              sleep $((5*n))   # backoff
            done
          done

      # Build using what’s cached; -o = offline (won’t hit 4thline)
      - name: Build (offline if repo is flaky)
        run: mvn -B -o -DskipTests clean package
