name: Build Cling

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Build Seamless dependency
        run: |
          git clone https://github.com/4thline/seamless.git
          cd seamless
          mvn clean install -DskipTests

      - name: Build Cling
        run: |
          mvn -B -U -DskipTests -Dmaven.javadoc.skip=true \
              -am -pl core clean package
      - name: Upload Cling JARs
        uses: actions/upload-artifact@v4
        with:
          name: cling-artifacts
          path: |
            core/target/*.jar
