# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          # temporarily disable Maven cache while debugging 401/lastUpdated issues
          # cache: maven

      - name: Write Maven settings (mirror + auth)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <servers>
              <server>
                <id>gh-mirror</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>gh-mirror</id>
                <url>https://maven.pkg.github.com/jolson20/cling</url>
                <mirrorOf>external:*,!central</mirrorOf>
              </mirror>
            </mirrors>
            <profiles>
              <profile>
                <id>repos</id>
                <repositories>
                  <repository>
                    <id>gh-mirror</id>
                    <url>https://maven.pkg.github.com/jolson20/cling</url>
                    <releases><enabled>true</enabled><updatePolicy>always</updatePolicy></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                  <repository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>repos</activeProfile>
            </activeProfiles>
          </settings>
          XML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      # optional sanity check that the package is reachable with your creds
      - name: Probe GH Packages auth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          curl -sSIL -u "$GITHUB_ACTOR:$GITHUB_TOKEN" \
            https://maven.pkg.github.com/jolson20/cling/org/seamless/seamless-util/1.1.2/seamless-util-1.1.2.pom

      - name: Build with a FRESH local repo (no old lastUpdated files)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          FRESH_REPO="$RUNNER_TEMP/m2repo_${GITHUB_RUN_ID}_${GITHUB_RUN_ATTEMPT}"
          echo "Using fresh repo: $FRESH_REPO"
          mvn -B -U -DskipTests -Dmaven.repo.local="$FRESH_REPO" clean package
