name: Seed Seamless to GitHub Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # required to publish to GitHub Packages

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Configure Maven to publish to GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          XML

      - name: Download Seamless artifacts from 4thline (with retries)
        env:
          RETRIES: "10"
        run: |
          set -e
          ARTIFS=(
            "org.seamless:seamless-util:1.1.2"
            "org.seamless:seamless-http:1.1.2"
            "org.seamless:seamless-xml:1.1.2"
          )
          for A in "${ARTIFS[@]}"; do
            n=0
            until [ $n -ge $RETRIES ]; do
              mvn -B -U dependency:get \
                -Dartifact="$A" \
                -DrepoUrl=https://4thline.org/m2 \
                -Dmaven.wagon.http.retryHandler.count=5 && break
              n=$((n+1))
              sleep $((5*n))
            done
          done

      - name: Deploy artifacts to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          OWNER=jolson20
          REPO=cling
          for A in seamless-util seamless-http seamless-xml; do
            JAR="$HOME/.m2/repository/org/seamless/$A/1.1.2/$A-1.1.2.jar"
            POM="$HOME/.m2/repository/org/seamless/$A/1.1.2/$A-1.1.2.pom"
            test -f "$JAR" && test -f "$POM"
            mvn -B deploy:deploy-file \
              -DgroupId=org.seamless \
              -DartifactId=$A \
              -Dversion=1.1.2 \
              -Dpackaging=jar \
              -Dfile="$JAR" \
              -DpomFile="$POM" \
              -DrepositoryId=github \
              -Durl="https://maven.pkg.github.com/${OWNER}/${REPO}"
          done
