name: Run Test without Nondex

on:
  workflow_dispatch:  # run manually

jobs:
  single-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: cling-jars
          path: core/target

      - name: Verify downloaded jars
        run: |
          echo "Downloaded JARs:"
          ls -lh core/target

      - name: Run single test
        run: |
          mvn -B -pl core \
            -Dtest=org.fourthline.cling.test.gena.EventXMLProcessingTest#writeReadRequestRecovering \
            -Dmaven.javadoc.skip=true test
